spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: spring-rapidoc-samples
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  mvc:
    problemdetails:
      enabled: true
  web:
    locale: en
    resources:
      cache:
        cachecontrol:
          max-age: 30d
  messages:
    fallback-to-system-locale: false
    use-code-as-default-message: true
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  task:
    execution:
      thread-name-prefix: AsyncExecutor
      pool:
        core-size: 20
        max-size: 100
        queue-capacity: 1000
        keep-alive: 60s
      shutdown:
        await-termination: true
        await-termination-period: 30s
    scheduling:
      thread-name-prefix: ScheduledTask-
      pool:
        size: 20
      shutdown:
        await-termination: true
        await-termination-period: 60s

management:
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
  prometheus:
    metrics:
      export:
        enabled: true
        step: 60
  observations:
    key-values:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    mail:
      enabled: false
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  info:
    git:
      mode: full
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    enabled: true


logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX}){faint} %clr(%5p){highlight} %clr(${PID:- }){magenta} --- [%clr(${spring.application.name:-}){green},%X{traceId:-},%X{spanId:-}] [%clr(%t){faint}] %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%clr(%wEx){red}'

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operationsSorter: method
    default-model-expand-depth: 1
    display-request-duration: true
    default-model-rendering: schema
    filter: true
    show-extensions: true
    try-it-out-enabled: true
  show-actuator: false
