server:
  port: 8080

spring:
  devtools:
    livereload:
      enabled: true
  messages:
    cache-duration: 1h
  mvc:
    cors:
      enabled: true
      allowed-origins: "http://localhost:9060"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
      allowed-headers: "Authorization,Content-Type,Accept,Cache-Control,X-Requested-With,Origin,Referer,User-Agent"
      allow-credentials: true
      max-age: 3600

logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    io.github.susimsek.apidoc: DEBUG
  async:
    queueSize: 10000
    discardingThreshold: 0
    maxFlushTime: 5000
    includeCallerData: false

management:
  tracing:
    enabled: false
  zipkin:
    tracing:
      endpoint: http://localhost:9411
